/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.itla.cobros;

import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author edgar
 */
public class CuentasFrame extends javax.swing.JFrame {

    DataBase dataBase = new DataBase();

    /**
     * Creates new form CuentasFrame
     */
    public CuentasFrame(DataBase dataBase) {
        this.dataBase = dataBase;
        initComponents();

        llenarTabla();


    }

    public void llenarTabla() {
        System.out.println("llenando la tabla");

        try {
            ResultSet rs = dataBase.getResultSet("select cobros.cuenta.id_cuenta, cobros.cuenta.cedula, cobros.cuenta.nombre, cobros.cuenta.apellido, cobros.cuenta.monto_deuda, cobros.cuenta.estatus  from cobros.cuenta");
            ResultSetMetaData metaDatos = rs.getMetaData();

            int numeroColumnas = metaDatos.getColumnCount();
            DefaultTableModel modelo = new DefaultTableModel();
            
            modelo.addColumn("No. Cuenta");
            modelo.addColumn("Cédula");
            modelo.addColumn("Nombres");
            modelo.addColumn("Apellidos");
            modelo.addColumn("Monto Deuda");
            modelo.addColumn("[ ||| ]");
            
            

            
            jTable2.setModel(modelo);
            
           
            

            while (rs.next()) {
              
                Object[] fila = new Object[numeroColumnas];

                for (int i = 0; i < numeroColumnas; i++) {
                    if(i == 5){
                    if(rs.getObject(i + 1).toString().equals("A")){
                        fila[i] = true;
                    }else{
                        fila[i] = false;
                    }
                    }else{
                        fila[i] = rs.getObject(i + 1);
                    
                    }
                    
                    //System.out.println("obj: "+rs.getObject(i + 1).toString());
                }
                // Se añade al modelo la fila completa.
                modelo.addRow(fila);
            }
             jTable2.getColumnModel().getColumn( 5 ).setCellEditor( new Celda_CheckBox() );
      
        jTable2.getColumnModel().getColumn( 5 ).setCellRenderer(new Render_CheckBox());



        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());

        }





    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(67, 67, 67)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 454, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 362, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
